AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Stack

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Value: !Ref Vpc
    Export:
      Name: VpcId
  InternetGatewayId:
    Value: !Ref InternetGateway
    Export:
      Name: InternetGatewayId


